package it.au.misure.util

import org.apache.spark.sql.types._

object Schemas {

  /**
    * Rappresenta il tipo di strutta della tabella hdfs denominata ''fm_quarti''.
    */

  val schemaQuarti = StructType(Array(
    StructField("codcontrdispquarti", StringType, true),
    StructField("coducquarti", StringType, true),
    StructField("podquarti", StringType, true),
    StructField("pivautentequarti", StringType, true),
    StructField("pivadistributorequarti", StringType, true),
    StructField("areaquarti", StringType, true),
    StructField("annoquarti", IntegerType, true),
    StructField("mesequarti", IntegerType, true),
    StructField("tipodato_e", IntegerType, true),
    StructField("tipodato_s", IntegerType, true),
    StructField("tensione", DoubleType, true),
    StructField("trattamento_o", StringType, true),
    StructField("potcontrimpl", DoubleType, true),
    StructField("potdisp", DoubleType, true),
    StructField("cifreatt", IntegerType, true),
    StructField("cifrerea", IntegerType, true),
    StructField("raccolta", StringType, true),
    StructField("validato", StringType, true),
    StructField("potmax", DoubleType, true),
    StructField("perdita", DoubleType, true),
    StructField("nomefile", StringType, true),
    StructField("annomesegiornodir", IntegerType, true),
    StructField("dataelaborazione", TimestampType, true),
    StructField("time_stamp", LongType, true),
    StructField("giornoquarti", IntegerType, true),
    StructField("e1", DoubleType, true),
    StructField("e2", DoubleType, true),
    StructField("e3", DoubleType, true),
    StructField("e4", DoubleType, true),
    StructField("e5", DoubleType, true),
    StructField("e6", DoubleType, true),
    StructField("e7", DoubleType, true),
    StructField("e8", DoubleType, true),
    StructField("e9", DoubleType, true),
    StructField("e10", DoubleType, true),
    StructField("e11", DoubleType, true),
    StructField("e12", DoubleType, true),
    StructField("e13", DoubleType, true),
    StructField("e14", DoubleType, true),
    StructField("e15", DoubleType, true),
    StructField("e16", DoubleType, true),
    StructField("e17", DoubleType, true),
    StructField("e18", DoubleType, true),
    StructField("e19", DoubleType, true),
    StructField("e20", DoubleType, true),
    StructField("e21", DoubleType, true),
    StructField("e22", DoubleType, true),
    StructField("e23", DoubleType, true),
    StructField("e24", DoubleType, true),
    StructField("e25", DoubleType, true),
    StructField("e26", DoubleType, true),
    StructField("e27", DoubleType, true),
    StructField("e28", DoubleType, true),
    StructField("e29", DoubleType, true),
    StructField("e30", DoubleType, true),
    StructField("e31", DoubleType, true),
    StructField("e32", DoubleType, true),
    StructField("e33", DoubleType, true),
    StructField("e34", DoubleType, true),
    StructField("e35", DoubleType, true),
    StructField("e36", DoubleType, true),
    StructField("e37", DoubleType, true),
    StructField("e38", DoubleType, true),
    StructField("e39", DoubleType, true),
    StructField("e40", DoubleType, true),
    StructField("e41", DoubleType, true),
    StructField("e42", DoubleType, true),
    StructField("e43", DoubleType, true),
    StructField("e44", DoubleType, true),
    StructField("e45", DoubleType, true),
    StructField("e46", DoubleType, true),
    StructField("e47", DoubleType, true),
    StructField("e48", DoubleType, true),
    StructField("e49", DoubleType, true),
    StructField("e50", DoubleType, true),
    StructField("e51", DoubleType, true),
    StructField("e52", DoubleType, true),
    StructField("e53", DoubleType, true),
    StructField("e54", DoubleType, true),
    StructField("e55", DoubleType, true),
    StructField("e56", DoubleType, true),
    StructField("e57", DoubleType, true),
    StructField("e58", DoubleType, true),
    StructField("e59", DoubleType, true),
    StructField("e60", DoubleType, true),
    StructField("e61", DoubleType, true),
    StructField("e62", DoubleType, true),
    StructField("e63", DoubleType, true),
    StructField("e64", DoubleType, true),
    StructField("e65", DoubleType, true),
    StructField("e66", DoubleType, true),
    StructField("e67", DoubleType, true),
    StructField("e68", DoubleType, true),
    StructField("e69", DoubleType, true),
    StructField("e70", DoubleType, true),
    StructField("e71", DoubleType, true),
    StructField("e72", DoubleType, true),
    StructField("e73", DoubleType, true),
    StructField("e74", DoubleType, true),
    StructField("e75", DoubleType, true),
    StructField("e76", DoubleType, true),
    StructField("e77", DoubleType, true),
    StructField("e78", DoubleType, true),
    StructField("e79", DoubleType, true),
    StructField("e80", DoubleType, true),
    StructField("e81", DoubleType, true),
    StructField("e82", DoubleType, true),
    StructField("e83", DoubleType, true),
    StructField("e84", DoubleType, true),
    StructField("e85", DoubleType, true),
    StructField("e86", DoubleType, true),
    StructField("e87", DoubleType, true),
    StructField("e88", DoubleType, true),
    StructField("e89", DoubleType, true),
    StructField("e90", DoubleType, true),
    StructField("e91", DoubleType, true),
    StructField("e92", DoubleType, true),
    StructField("e93", DoubleType, true),
    StructField("e94", DoubleType, true),
    StructField("e95", DoubleType, true),
    StructField("e96", DoubleType, true),
    StructField("e97", DoubleType, true),
    StructField("e98", DoubleType, true),
    StructField("e99", DoubleType, true),
    StructField("e100", DoubleType, true),
    StructField("er1", DoubleType, true),
    StructField("er2", DoubleType, true),
    StructField("er3", DoubleType, true),
    StructField("er4", DoubleType, true),
    StructField("er5", DoubleType, true),
    StructField("er6", DoubleType, true),
    StructField("er7", DoubleType, true),
    StructField("er8", DoubleType, true),
    StructField("er9", DoubleType, true),
    StructField("er10", DoubleType, true),
    StructField("er11", DoubleType, true),
    StructField("er12", DoubleType, true),
    StructField("er13", DoubleType, true),
    StructField("er14", DoubleType, true),
    StructField("er15", DoubleType, true),
    StructField("er16", DoubleType, true),
    StructField("er17", DoubleType, true),
    StructField("er18", DoubleType, true),
    StructField("er19", DoubleType, true),
    StructField("er20", DoubleType, true),
    StructField("er21", DoubleType, true),
    StructField("er22", DoubleType, true),
    StructField("er23", DoubleType, true),
    StructField("er24", DoubleType, true),
    StructField("er25", DoubleType, true),
    StructField("er26", DoubleType, true),
    StructField("er27", DoubleType, true),
    StructField("er28", DoubleType, true),
    StructField("er29", DoubleType, true),
    StructField("er30", DoubleType, true),
    StructField("er31", DoubleType, true),
    StructField("er32", DoubleType, true),
    StructField("er33", DoubleType, true),
    StructField("er34", DoubleType, true),
    StructField("er35", DoubleType, true),
    StructField("er36", DoubleType, true),
    StructField("er37", DoubleType, true),
    StructField("er38", DoubleType, true),
    StructField("er39", DoubleType, true),
    StructField("er40", DoubleType, true),
    StructField("er41", DoubleType, true),
    StructField("er42", DoubleType, true),
    StructField("er43", DoubleType, true),
    StructField("er44", DoubleType, true),
    StructField("er45", DoubleType, true),
    StructField("er46", DoubleType, true),
    StructField("er47", DoubleType, true),
    StructField("er48", DoubleType, true),
    StructField("er49", DoubleType, true),
    StructField("er50", DoubleType, true),
    StructField("er51", DoubleType, true),
    StructField("er52", DoubleType, true),
    StructField("er53", DoubleType, true),
    StructField("er54", DoubleType, true),
    StructField("er55", DoubleType, true),
    StructField("er56", DoubleType, true),
    StructField("er57", DoubleType, true),
    StructField("er58", DoubleType, true),
    StructField("er59", DoubleType, true),
    StructField("er60", DoubleType, true),
    StructField("er61", DoubleType, true),
    StructField("er62", DoubleType, true),
    StructField("er63", DoubleType, true),
    StructField("er64", DoubleType, true),
    StructField("er65", DoubleType, true),
    StructField("er66", DoubleType, true),
    StructField("er67", DoubleType, true),
    StructField("er68", DoubleType, true),
    StructField("er69", DoubleType, true),
    StructField("er70", DoubleType, true),
    StructField("er71", DoubleType, true),
    StructField("er72", DoubleType, true),
    StructField("er73", DoubleType, true),
    StructField("er74", DoubleType, true),
    StructField("er75", DoubleType, true),
    StructField("er76", DoubleType, true),
    StructField("er77", DoubleType, true),
    StructField("er78", DoubleType, true),
    StructField("er79", DoubleType, true),
    StructField("er80", DoubleType, true),
    StructField("er81", DoubleType, true),
    StructField("er82", DoubleType, true),
    StructField("er83", DoubleType, true),
    StructField("er84", DoubleType, true),
    StructField("er85", DoubleType, true),
    StructField("er86", DoubleType, true),
    StructField("er87", DoubleType, true),
    StructField("er88", DoubleType, true),
    StructField("er89", DoubleType, true),
    StructField("er90", DoubleType, true),
    StructField("er91", DoubleType, true),
    StructField("er92", DoubleType, true),
    StructField("er93", DoubleType, true),
    StructField("er94", DoubleType, true),
    StructField("er95", DoubleType, true),
    StructField("er96", DoubleType, true),
    StructField("er97", DoubleType, true),
    StructField("er98", DoubleType, true),
    StructField("er99", DoubleType, true),
    StructField("er100", DoubleType, true)
  ))
  
    val schemaQuartiCreaFlusso = StructType(Array(
    StructField("coducquarti", StringType, true),
    StructField("podquarti", StringType, true),
    StructField("annoquarti", IntegerType, true),
    StructField("mesequarti", IntegerType, true),
    StructField("pivadistributorequarti", StringType, true),
    StructField("codcontrdispquarti", StringType, true),
    StructField("areaquarti", StringType, true),
    StructField("pivautentequarti", StringType, true),
    StructField("tipodato_e", IntegerType, true),
    StructField("tipodato_s", IntegerType, true),
    StructField("tensione", DoubleType, true),
    StructField("trattamento_o", StringType, true),
    StructField("potcontrimpl", DoubleType, true),
    StructField("potdisp", DoubleType, true),
    StructField("cifreatt", IntegerType, true),
    StructField("cifrerea", IntegerType, true),
    StructField("raccolta", StringType, true),
    StructField("validato", StringType, true),
    StructField("potmax", DoubleType, true),
    StructField("perdita", DoubleType, true),
    StructField("nomefile", StringType, true),
    StructField("annomesegiornodir", IntegerType, true),
    StructField("dataelaborazione", TimestampType, true),
    StructField("time_stamp", LongType, true),
    StructField("giornoquarti", IntegerType, true),
    StructField("e1", DoubleType, true),
    StructField("e2", DoubleType, true),
    StructField("e3", DoubleType, true),
    StructField("e4", DoubleType, true),
    StructField("e5", DoubleType, true),
    StructField("e6", DoubleType, true),
    StructField("e7", DoubleType, true),
    StructField("e8", DoubleType, true),
    StructField("e9", DoubleType, true),
    StructField("e10", DoubleType, true),
    StructField("e11", DoubleType, true),
    StructField("e12", DoubleType, true),
    StructField("e13", DoubleType, true),
    StructField("e14", DoubleType, true),
    StructField("e15", DoubleType, true),
    StructField("e16", DoubleType, true),
    StructField("e17", DoubleType, true),
    StructField("e18", DoubleType, true),
    StructField("e19", DoubleType, true),
    StructField("e20", DoubleType, true),
    StructField("e21", DoubleType, true),
    StructField("e22", DoubleType, true),
    StructField("e23", DoubleType, true),
    StructField("e24", DoubleType, true),
    StructField("e25", DoubleType, true),
    StructField("e26", DoubleType, true),
    StructField("e27", DoubleType, true),
    StructField("e28", DoubleType, true),
    StructField("e29", DoubleType, true),
    StructField("e30", DoubleType, true),
    StructField("e31", DoubleType, true),
    StructField("e32", DoubleType, true),
    StructField("e33", DoubleType, true),
    StructField("e34", DoubleType, true),
    StructField("e35", DoubleType, true),
    StructField("e36", DoubleType, true),
    StructField("e37", DoubleType, true),
    StructField("e38", DoubleType, true),
    StructField("e39", DoubleType, true),
    StructField("e40", DoubleType, true),
    StructField("e41", DoubleType, true),
    StructField("e42", DoubleType, true),
    StructField("e43", DoubleType, true),
    StructField("e44", DoubleType, true),
    StructField("e45", DoubleType, true),
    StructField("e46", DoubleType, true),
    StructField("e47", DoubleType, true),
    StructField("e48", DoubleType, true),
    StructField("e49", DoubleType, true),
    StructField("e50", DoubleType, true),
    StructField("e51", DoubleType, true),
    StructField("e52", DoubleType, true),
    StructField("e53", DoubleType, true),
    StructField("e54", DoubleType, true),
    StructField("e55", DoubleType, true),
    StructField("e56", DoubleType, true),
    StructField("e57", DoubleType, true),
    StructField("e58", DoubleType, true),
    StructField("e59", DoubleType, true),
    StructField("e60", DoubleType, true),
    StructField("e61", DoubleType, true),
    StructField("e62", DoubleType, true),
    StructField("e63", DoubleType, true),
    StructField("e64", DoubleType, true),
    StructField("e65", DoubleType, true),
    StructField("e66", DoubleType, true),
    StructField("e67", DoubleType, true),
    StructField("e68", DoubleType, true),
    StructField("e69", DoubleType, true),
    StructField("e70", DoubleType, true),
    StructField("e71", DoubleType, true),
    StructField("e72", DoubleType, true),
    StructField("e73", DoubleType, true),
    StructField("e74", DoubleType, true),
    StructField("e75", DoubleType, true),
    StructField("e76", DoubleType, true),
    StructField("e77", DoubleType, true),
    StructField("e78", DoubleType, true),
    StructField("e79", DoubleType, true),
    StructField("e80", DoubleType, true),
    StructField("e81", DoubleType, true),
    StructField("e82", DoubleType, true),
    StructField("e83", DoubleType, true),
    StructField("e84", DoubleType, true),
    StructField("e85", DoubleType, true),
    StructField("e86", DoubleType, true),
    StructField("e87", DoubleType, true),
    StructField("e88", DoubleType, true),
    StructField("e89", DoubleType, true),
    StructField("e90", DoubleType, true),
    StructField("e91", DoubleType, true),
    StructField("e92", DoubleType, true),
    StructField("e93", DoubleType, true),
    StructField("e94", DoubleType, true),
    StructField("e95", DoubleType, true),
    StructField("e96", DoubleType, true),
    StructField("e97", DoubleType, true),
    StructField("e98", DoubleType, true),
    StructField("e99", DoubleType, true),
    StructField("e100", DoubleType, true)
//    ,
//    StructField("er1", DoubleType, true),
//    StructField("er2", DoubleType, true),
//    StructField("er3", DoubleType, true),
//    StructField("er4", DoubleType, true),
//    StructField("er5", DoubleType, true),
//    StructField("er6", DoubleType, true),
//    StructField("er7", DoubleType, true),
//    StructField("er8", DoubleType, true),
//    StructField("er9", DoubleType, true),
//    StructField("er10", DoubleType, true),
//    StructField("er11", DoubleType, true),
//    StructField("er12", DoubleType, true),
//    StructField("er13", DoubleType, true),
//    StructField("er14", DoubleType, true),
//    StructField("er15", DoubleType, true),
//    StructField("er16", DoubleType, true),
//    StructField("er17", DoubleType, true),
//    StructField("er18", DoubleType, true),
//    StructField("er19", DoubleType, true),
//    StructField("er20", DoubleType, true),
//    StructField("er21", DoubleType, true),
//    StructField("er22", DoubleType, true),
//    StructField("er23", DoubleType, true),
//    StructField("er24", DoubleType, true),
//    StructField("er25", DoubleType, true),
//    StructField("er26", DoubleType, true),
//    StructField("er27", DoubleType, true),
//    StructField("er28", DoubleType, true),
//    StructField("er29", DoubleType, true),
//    StructField("er30", DoubleType, true),
//    StructField("er31", DoubleType, true),
//    StructField("er32", DoubleType, true),
//    StructField("er33", DoubleType, true),
//    StructField("er34", DoubleType, true),
//    StructField("er35", DoubleType, true),
//    StructField("er36", DoubleType, true),
//    StructField("er37", DoubleType, true),
//    StructField("er38", DoubleType, true),
//    StructField("er39", DoubleType, true),
//    StructField("er40", DoubleType, true),
//    StructField("er41", DoubleType, true),
//    StructField("er42", DoubleType, true),
//    StructField("er43", DoubleType, true),
//    StructField("er44", DoubleType, true),
//    StructField("er45", DoubleType, true),
//    StructField("er46", DoubleType, true),
//    StructField("er47", DoubleType, true),
//    StructField("er48", DoubleType, true),
//    StructField("er49", DoubleType, true),
//    StructField("er50", DoubleType, true),
//    StructField("er51", DoubleType, true),
//    StructField("er52", DoubleType, true),
//    StructField("er53", DoubleType, true),
//    StructField("er54", DoubleType, true),
//    StructField("er55", DoubleType, true),
//    StructField("er56", DoubleType, true),
//    StructField("er57", DoubleType, true),
//    StructField("er58", DoubleType, true),
//    StructField("er59", DoubleType, true),
//    StructField("er60", DoubleType, true),
//    StructField("er61", DoubleType, true),
//    StructField("er62", DoubleType, true),
//    StructField("er63", DoubleType, true),
//    StructField("er64", DoubleType, true),
//    StructField("er65", DoubleType, true),
//    StructField("er66", DoubleType, true),
//    StructField("er67", DoubleType, true),
//    StructField("er68", DoubleType, true),
//    StructField("er69", DoubleType, true),
//    StructField("er70", DoubleType, true),
//    StructField("er71", DoubleType, true),
//    StructField("er72", DoubleType, true),
//    StructField("er73", DoubleType, true),
//    StructField("er74", DoubleType, true),
//    StructField("er75", DoubleType, true),
//    StructField("er76", DoubleType, true),
//    StructField("er77", DoubleType, true),
//    StructField("er78", DoubleType, true),
//    StructField("er79", DoubleType, true),
//    StructField("er80", DoubleType, true),
//    StructField("er81", DoubleType, true),
//    StructField("er82", DoubleType, true),
//    StructField("er83", DoubleType, true),
//    StructField("er84", DoubleType, true),
//    StructField("er85", DoubleType, true),
//    StructField("er86", DoubleType, true),
//    StructField("er87", DoubleType, true),
//    StructField("er88", DoubleType, true),
//    StructField("er89", DoubleType, true),
//    StructField("er90", DoubleType, true),
//    StructField("er91", DoubleType, true),
//    StructField("er92", DoubleType, true),
//    StructField("er93", DoubleType, true),
//    StructField("er94", DoubleType, true),
//    StructField("er95", DoubleType, true),
//    StructField("er96", DoubleType, true),
//    StructField("er97", DoubleType, true),
//    StructField("er98", DoubleType, true),
//    StructField("er99", DoubleType, true),
//    StructField("er100", DoubleType, true)
  ))
  
  /**
    * Rappresenta il tipo di strutta della tabella hdfs denominata ''tracciati_misure_inammissibili''.
    */
  val schemaReport = StructType(Array(
    StructField("codice", StringType, true),
    StructField("nomefile", StringType, true),
    StructField("messaggio", StringType, true),
    StructField("dataelaborazione", TimestampType, true),
    StructField("annomese", IntegerType, true)
  ))
  
  val schemaNomeXmlScartati = StructType(Array(
    StructField("nomefiletmp", StringType, true)
    ))
    

  val schemaOre = StructType(Array(
    StructField("pivadistributore", StringType, true),
    StructField("pivautente", StringType, true),
    StructField("pod", StringType, true),
    StructField("anno", IntegerType, true),
    StructField("mese", IntegerType, true),
    StructField("giorno", IntegerType, true),
    StructField("area", StringType, true),
    StructField("validato", StringType, true),
    StructField("nomefile", StringType, true),
    StructField("codcontrdisp", StringType, true),
    StructField("coduc", StringType, true),
    StructField("tipodato_e", IntegerType, true),
    StructField("tipodato_s", IntegerType, true),
    StructField("tensione", DoubleType, true),
    StructField("trattamento_o", StringType, true),
    StructField("potcontrimpl", DoubleType, true),
    StructField("potdisp", DoubleType, true),
    StructField("cifreatt", IntegerType, true),
    StructField("cifrerea", IntegerType, true),
    StructField("raccolta", StringType, true),
    StructField("potmax", DoubleType, true),
    StructField("perdita", DoubleType, true),
    StructField("annomesegiornodir", IntegerType, true),
    StructField("h1", DoubleType, true),
    StructField("h2", DoubleType, true),
    StructField("h3", DoubleType, true),
    StructField("h4", DoubleType, true),
    StructField("h5", DoubleType, true),
    StructField("h6", DoubleType, true),
    StructField("h7", DoubleType, true),
    StructField("h8", DoubleType, true),
    StructField("h9", DoubleType, true),
    StructField("h10", DoubleType, true),
    StructField("h11", DoubleType, true),
    StructField("h12", DoubleType, true),
    StructField("h13", DoubleType, true),
    StructField("h14", DoubleType, true),
    StructField("h15", DoubleType, true),
    StructField("h16", DoubleType, true),
    StructField("h17", DoubleType, true),
    StructField("h18", DoubleType, true),
    StructField("h19", DoubleType, true),
    StructField("h20", DoubleType, true),
    StructField("h21", DoubleType, true),
    StructField("h22", DoubleType, true),
    StructField("h23", DoubleType, true),
    StructField("h24", DoubleType, true),
    StructField("h25", DoubleType, true),
    StructField("time_stamp", LongType, true),
    StructField("versione", LongType, true),
    StructField("dataelaborazione", TimestampType, true),
    StructField("flaguddpod", StringType, true),
    StructField("stato", StringType, true),
    StructField("trattamento", StringType, true),
    StructField("flagarea", StringType, true),
    StructField("n_id_udd", StringType, true),
    StructField("t_piva", StringType, true),
    StructField("n_id_distr", StringType, true),
    StructField("n_id_distr_rif", StringType, true),
    StructField("flag_validazione", StringType, true)
  ))
  
}
